"""add job counters

Revision ID: 845baf25f302
Revises: 
Create Date: 2026-03-17 08:44:52.647188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845baf25f302'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('found_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('saved_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('duplicate_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('error_count', sa.Integer(), nullable=True))
    op.drop_index('ix_products_product_url', table_name='products')
    op.create_index(op.f('ix_products_product_url'), 'products', ['product_url'], unique=False)
    op.create_index('ix_products_job_url', 'products', ['job_id', 'product_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_job_url', table_name='products')
    op.drop_index(op.f('ix_products_product_url'), table_name='products')
    op.create_index('ix_products_product_url', 'products', ['product_url'], unique=False)
    op.drop_column('jobs', 'error_count')
    op.drop_column('jobs', 'duplicate_count')
    op.drop_column('jobs', 'saved_count')
    op.drop_column('jobs', 'found_count')
    # ### end Alembic commands ###
